on: [push]

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlclient
          version: 2019
          sa-password: Password12
          show-log: true

      - name: Run sqlcmd
        run: sqlcmd -S localhost -U sa -P Password12 -d tempdb -Q "SELECT @@version;"
